int main() {
    try {
        
    } catch (bad_cast e) {
        // ...
    } catch (overflow_error e) {
        // ...
    } catch (underflow_error e) {
        // ...
    } catch (range_error e) {
        // ...
    } catch (runtime_error e) {
        // ...
    } catch (domain_error e) {
        // ...
    } catch (invalid_argument e) {
        // ...
    } catch (out_of_range e) {
        // ...
    } catch (length_err e) {
        // ...
    } catch (logic_error e) {
        // ...
    } catch (bad_alloc e) {
        // ...
    } catch (exception e) {
        // ...
    }
    return 0;
}
